# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)

In [3]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [4]:
print(A.ndim)

2


In [5]:
print(A.shape)

(3, 5)


In [6]:
print(A.size) 

15


In [7]:
print(type(A))

<class 'numpy.ndarray'>


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [8]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [9]:
print(np.subtract(B, C))
print()
print(np.multiply(B, C))
print()
print(B@C)
print()
print(B.dot(C))

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


# Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [10]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
result = np.exp(B) #exponention of each number
print(result)
print()

min_value = np.min(B) #minimum value in the whole matrix
print(min_value)
print()

min_value_each_row = np.min(B, axis = 1) #minimum value in each row
print(min_value_each_row)
print()

min_value_each_column = np.min(B, axis = 0) #minimum value in each column
print(min_value_each_column)
print()

index_value = np.argmin(B) #index value for the minimum value in the whole matrix
print(index_value)
print()

index_value_each_row = np.argmin(B, axis = 1) #index value for the minimum value in each row
print(index_value_each_row)
print()

print(np.sum(B)) #sum for all elements
print()

print(np.mean(B, axis = 0)) #mean for each column.
print()

print(np.median(B, axis = 0)) #median for each column.

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

1

[1 4 7]

[1 2 3]

0

[0 0 0]

45

[4. 5. 6.]

[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [12]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [13]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [14]:
# It will return a whole row 

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [15]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [16]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [17]:
for i in A:
    for element in i:
        print(element) #nested loop

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [18]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


It means that our array will consist two matrises with three rows. -1 adapts quantity of columns that makes our arange of 30 to work.

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [19]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [20]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [21]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)
print()
print(A + b)

[[1 2]
 [3 4]]
[2 2]

[[3 4]
 [5 6]]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [22]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print(B)
print(C)
print(D)
print(E)

[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [23]:
def add_mult_matrices(matrice_1, matrice_2, add_or_multiply):
    
    if(add_or_multiply == 'add' or add_or_multiply == 'multiply'): 
    
        if (isinstance(matrice_1, np.ndarray) and isinstance(matrice_2, np.ndarray)):

            if add_or_multiply == 'add':
                if matrice_1.shape == matrice_2.shape:
                    return matrice_1 + matrice_2
                else:
                    raise ValueError('Mismatch in matrix shape for addition.')
            else:
                if matrice_1.shape[1] == matrice_2.shape[0]:
                    return matrice_1 @ matrice_2
                else:
                    raise ValueError('Columns are not equal to amount of rows for multiplication')

        else:
            raise Exception('Use matrices')  

    else:
        raise Exception('Use "add" or "multiply"')



In [24]:
# B - 2A
add_mult_matrices(B, -2*A, 'add') 

array([[ 0, -4,  3],
       [ 0, -2, -4]])

In [25]:
# 3C - E
add_mult_matrices(3*C, -E, 'add')

ValueError: Mismatch in matrix shape for addition.

In [26]:
# AC
add_mult_matrices(A, C, 'multiply')

ValueError: Columns are not equal to amount of rows for multiplication

In [27]:
# CD
add_mult_matrices(C, D, 'multiply')

array([[11, 10],
       [10, 11]])

In [28]:
# CB
add_mult_matrices(C, B, 'multiply')

array([[  8, -10,  -3],
       [ 10,  -8,   0]])

**Chap2. Question 2**

In [29]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

AB = add_mult_matrices(A, B, 'multiply')
AC = add_mult_matrices(A, C, 'multiply')

AB_equals_AC = (AB == AC).all()
B_equals_C = (B == C).all()

print('AB Equals AC: ' , AB_equals_AC)  
print('B Equals C: ' ,B_equals_C)  

AB Equals AC:  True
B Equals C:  False


**Chap2. Question 3**

In [30]:
A = np.array([[1, 1, 1], [1, 2, 3], [1, 3, 4]])
D = np.array([[2, 0, 0], [0, 3, 0], [0, 0, 4]])

print('AD',  add_mult_matrices(A, D, 'multiply'))
print()
print('DA',  add_mult_matrices(D, A, 'multiply'))

AD [[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]

DA [[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.11, Question 2**

In [31]:
Matrice_1 = np.array([[1, -1], [-1, 1]])
Matrice_2 = np.array([[-1, 1], [1, -1]])

print(add_mult_matrices (Matrice_1, Matrice_2, 'multiply'))

[[-2  2]
 [ 2 -2]]


**Chap 6. Question 1**

In [32]:
M1 = np.array([[5, 6], [4, 5]])
M2 = np.array([[6, 4], [3, 3]])

M1_inv = np.linalg.inv(M1)
print(M1_inv)

print(M1 @ M1_inv)
print(np.allclose(M1 @ M1_inv, np.eye(2)))

[[ 5. -6.]
 [-4.  5.]]
[[ 1.00000000e+00  0.00000000e+00]
 [-2.66453526e-15  1.00000000e+00]]
True


In [33]:
M2_inv = np.linalg.inv(M2)
print(M2_inv)

print(M2 @ M2_inv)
print(np.allclose(M2 @ M2_inv, np.eye(2)))

[[ 0.5        -0.66666667]
 [-0.5         1.        ]]
[[1. 0.]
 [0. 1.]]
True


**Quiz p.19, Question 3**

In [34]:
M = np.array([[2, 2], [1, 2]])
M_inv = np.linalg.inv(M)
print(M_inv)

print(M @ M_inv)
print(np.allclose(M @ M_inv, np.eye(2)))

[[ 1.  -1. ]
 [-0.5  1. ]]
[[1. 0.]
 [0. 1.]]
True


**Chap10. Question 1 a)**

In [35]:
A = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
b = np.array([-7, 5, 2])
print(A)
print(b)

[[ 3 -7 -2]
 [-3  5  1]
 [ 6 -4  0]]
[-7  5  2]


In [36]:
x = np.linalg.solve(A, b)
print(x)

[ 3.  4. -6.]


In [37]:
A @ x

array([-7.,  5.,  2.])

**Chap10. Question 1 b)**

In [38]:
A = np.array([[1, -2, 3], [-1, 3, -1], [2, -5, 5]])
b = np.array([1, -1, 1])

x = np.linalg.solve(A, b)
print(x)

A @ x

[ 8.  2. -1.]


array([ 1., -1.,  1.])

**Chap 12. Question 1**

In [39]:
Matrice = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
Matrice_inv = np.linalg.inv(Matrice)
print(Matrice_inv)

print(np.allclose(Matrice @ Matrice_inv, np.eye(3)))

[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]
True


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [40]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [41]:
# If it´s a view it will return an array and if it´s a copy, it will return "none"
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [42]:
# It will be changed because v2 is a view and it makes v2 and v1 connected to each other.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
